FROM ubuntu:24.04

# Install dependencies
RUN apt-get update && apt-get install -y ca-certificates mariadb-server redis-server tzdata libsqlite3-dev pkg-config wget && rm -rf /var/lib/apt/lists/*

# Install Go 1.25.5
RUN wget https://dl.google.com/go/go1.25.5.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.25.5.linux-amd64.tar.gz && \
    rm go1.25.5.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin

RUN go version
ENV TZ=Asia/Makassar
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

COPY . .

# Download dependencies
RUN go mod download

# Copy MariaDB config for binary logging
COPY mariadb-binlog.cnf /etc/mysql/mariadb.conf.d/

# Copy start script
COPY start.sh .

# Make scripts executable
RUN chmod +x start.sh

COPY config ./config
COPY switch-config.sh ./switch-config.sh
RUN mkdir -p ./log ./whatsmeow

# # Make switch-config.sh executable and switch to production mode
# RUN chmod +x ./switch-config.sh && ./switch-config.sh prod

# EXPOSE 11225

# Keep container running for manual build and run
ENTRYPOINT ["tail", "-f", "/dev/null"]